version: '3.7'
services:
  backend:
    container_name: backend
    build: .
    restart: always
    env_file: ./.env.example
    ports:
      -  8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
     - ./:/home/app/backend
     - static_volume:/home/app/backend/static
  postgres_db:
    image: postgres:13.0-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=iha
      - POSTGRES_PASSWORD=iha
      - POSTGRES_DB=iha_dev

volumes:
  static_volume:
  postgres_data:
