name: Django CI

on:
  push:
  
    branches: [ try ]
  pull_request:
    branches: [ try ]

jobs:
  Deploy-luploq:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy iha
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST_DNS }}
          key: ${{ secrets.EC2_SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: cd /IHAKiralama